import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";

const hindSiliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["bengali"],
});

export const metadata: Metadata = {
  title: "Tarunner Thikana Blood Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hindSiliguri.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
